### PR TITLE
Update mp

### PR DESCRIPTION
**Pull request by melpetera**
I coded several changes in this module as mentioned in the corresponding readme file. 

@lecorguille could you check if you are ok with the changes suggested? We can discuss if you want. 

What I did not change but may deserve some refreshing:
- the "workflow position" picture
- the working example in help section
- the 'description' part of the .shed.yml (it does not match what this tool is meant for)

### CODE REVIEW

**Comment by melpetera** [comment]
Seems that the pdf file failed in test. Is this due to the fact that it is a PDF file or to the fact that I generated it with windows (which is not the case for the tabular one that I generated via Galaxy)?

**Comment by lecorguille** [comment]
@melpetera Many many thanks!

I have just modify the test itself and apply a `round(x,10)` on the padj 

There were too many digit after the coma and it was to machine/OS dependent.

```R
varinfoTab=cbind(varinfoTab, round(t(aovAdjPValue),10), selected.var)
```

Are you ok with that?

**Comment by melpetera** [comment]
Thanks @lecorguille ! Your changes are ok for me. 

Do you have an opinion concerning the 3 "refreshing" points? (workflow position, working example, .shed.yml description)

**Comment by lecorguille** [comment]
Can we imagine removing the workflow position, working example? It's easier to maintain without?
About the .shed.yml, if you have a little sentence to indeed give more information, you are welcome!
Please add your affiliation as author, you deserve it (if you're not to ashamed to be associated with this tools :/)

**Comment by melpetera** [comment]
I agree about removing workflow position and working example: it is way simplier to maintain and not crucial for a module as this one 👍 

I added my affiliation too. You know your scripts are very clear (well organised, well commented) so it is a pleasure to work on it ;)

I also updated the .shed.yml; I simply put the text of the module description which is perfect for this. 

Ready for the merge on dev and final tests on dev instance? :)

**Comment by lecorguille** [comment]
@melpetera Available into the galaxydev instance

**Pull request merged**
